[build]
rustc-wrapper = "/home/yilisharcs/.cargo/bin/sccache"

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]
