# Will show new commits associated with new nightly release if enabled
enable_nightly_info = true

# Compile neovim nightly or a certain hash version as a release build (slightly improved performance, no debug info)
enable_release_build = true

# The folder in which neovim versions will be installed too, bob will error if this option is specified but the folder doesn't exist
downloads_location = "$HOME/.local/share/bob"

# The path in which the used neovim version will be located in
installation_location = "/home/user/.local/share/bob/nvim-bin"

# The path to a file that will hold the neovim version string, useful for config version tracking, bob will error if the specified file is not a valid file path
version_sync_file_location = "/home/user/.config/nvim/nvim.version"

# The amount of rollbacks before bob starts to delete older ones, can be up to 225
rollback_limit = 3

# github or github mirror
github_mirror = "https://github.com"
